const mongoose = require('mongoose')
// const User = require('./user')
//schema for product
const ProductSchema = mongoose.Schema({
    //name, price, owner are the rows
    name:{type:String,required:true},
    price:{type:Number,required:true},
    owner:{type:mongoose.Schema.Types.ObjectID,ref:'User'}
})

//model set and exported

const Product = mongoose.model("Product",ProductSchema,"products")
module.exports = Product

// 1) User (_id will be autogenerated)
// a. name (String, required)
// b. user_name(String, required)
// c. balance(Number, default:100)
// In addition, you will be creating a virtual field called “items” that will hold the products the user
// owns.
// 2) Product (_id will be autogenerated)
// a. name(String, required)
// b. price(Number, required)
// c. owner(ObjectID, will reference the _id field of a document in the User collection)

// userSchema.virtual('posts',{
//     ref:'Post',
//     localField:'_id',
//     foreignField:'author'
//     })
//     userSchema.set('toJSON',{virtuals: true})
//     userSchema.set('toObject',{virtuals:true})
//     This essentially creates a field in the User
//     Model that will store the user posts.
//     However, this is a virtual field, so no actual
//     post data is stored. Instead, the
//     • ref: Tells Mongoose which collection to
//     look at
//     • localField: Tells mongoose which field to
//     match in the user collection
//     • foreignField: Tells mongoose which field to
//     match in the posts collection
//     **The name of the virtual field(posts) can be
//     named anything (e.g. entries, blogs etc.)The toJSON and toObject configuration simply means when a
//     user document is retrieved and made available as a plain JS
//     object/JSON string, whether or not the posts should be
//     included as well. By default, this is false.